"""Initial empty migration

Revision ID: 84b4fc6383e6
Revises: 
Create Date: 2026-02-22 20:57:32.652826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b4fc6383e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('dms_provider', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('dms_api_key', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('dms_oauth_token', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('gemini_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'gemini_api_key')
    op.drop_column('user_profiles', 'dms_oauth_token')
    op.drop_column('user_profiles', 'dms_api_key')
    op.drop_column('user_profiles', 'dms_provider')
    # ### end Alembic commands ###
